### ISSUE TITLE
Update the README to show the number of blocked domains on each build

### ISSUE THREAD

**Issue by T145** [T145/black-mirror#16]
`markdown README.md | tidy -f errs.txt -i -asxhtml | xmlstarlet ed --update '//td[@id="domain_size"]' --value '123'`
```html
        <!-- small box -->
        <div class="small-box bg-red no-user-select" title="Blocking list updated 01:54 (hh:mm) ago">
            <div class="inner">
                <p>Domains on Blocklist</p>
                <h3 class="statistic"><span id="domains_being_blocked" class="">82,723</span></h3>
            </div>
            <div class="icon">
                <svg class="svg-inline--fa fa-list-alt fa-w-16" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="list-alt" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M464 480H48c-26.51 0-48-21.49-48-48V80c0-26.51 21.49-48 48-48h416c26.51 0 48 21.49 48 48v352c0 26.51-21.49 48-48 48zM128 120c-22.091 0-40 17.909-40 40s17.909 40 40 40 40-17.909 40-40-17.909-40-40-40zm0 96c-22.091 0-40 17.909-40 40s17.909 40 40 40 40-17.909 40-40-17.909-40-40-40zm0 96c-22.091 0-40 17.909-40 40s17.909 40 40 40 40-17.909 40-40-17.909-40-40-40zm288-136v-32c0-6.627-5.373-12-12-12H204c-6.627 0-12 5.373-12 12v32c0 6.627 5.373 12 12 12h200c6.627 0 12-5.373 12-12zm0 96v-32c0-6.627-5.373-12-12-12H204c-6.627 0-12 5.373-12 12v32c0 6.627 5.373 12 12 12h200c6.627 0 12-5.373 12-12zm0 96v-32c0-6.627-5.373-12-12-12H204c-6.627 0-12 5.373-12 12v32c0 6.627 5.373 12 12 12h200c6.627 0 12-5.373 12-12z"></path></svg><!-- <i class="fas fa-list-alt"></i> Font Awesome fontawesome.com -->
            </div>
        </div>
```

```css
.small-box span {
  transition-duration: 0.5s;
}

.small-box span.glow {
  text-shadow: 0 0 5px currentColor;
}

.box,
.small-box {
  border-radius: 10px;
}

.bg-red {
  background-color: #913225 !important;
}

.no-user-select {
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

https://github.com/pi-hole/AdminLTE/blob/master/img/donate.gif
